name: OWASP ZAP
on: push
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://carpathian-nightmare.web.app'